import type { Issue, ScanResult, Severity } from '../types/index.js';

function severityEmoji(severity: Severity): string {
  return {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
  }[severity];
}

function severityLabel(severity: Severity): string {
  return severity.charAt(0).toUpperCase() + severity.slice(1);
}

function countBySeverity(issues: Issue[]): Record<Severity, number> {
  return {
    critical: issues.filter((issue) => issue.severity === 'critical').length,
    high: issues.filter((issue) => issue.severity === 'high').length,
    medium: issues.filter((issue) => issue.severity === 'medium').length,
    low: issues.filter((issue) => issue.severity === 'low').length,
  };
}

function frameworkLabel(framework: string): string {
  return {
    nextjs: 'Next.js',
    vite: 'Vite',
    react: 'React',
    express: 'Node/Express',
  }[framework] ?? 'Unknown';
}

export function generateMarkdownReport(result: ScanResult): string {
  const { projectInfo: info, issues, targetDir, scannedAt } = result;
  const counts = countBySeverity(issues);
  const lines: string[] = [
    '# 🛡️ Project Health Report',
    '',
    '> Generated by **CodeEq v0.2**',
    `> Scanned: \`${scannedAt}\``,
    `> Target: \`${targetDir}\``,
    '',
    '---',
    '',
    '## Project Info',
    '',
    '| Property | Value |',
    '|----------|-------|',
    `| **Name** | \`${info.name}\` |`,
    `| **Framework** | ${frameworkLabel(info.framework)} |`,
    `| **Language** | ${info.language === 'typescript' ? 'TypeScript' : 'JavaScript'} |`,
    `| **Package Manager** | ${info.packageManager} |`,
    `| **Supabase** | ${info.usesSupabase ? '✅ Yes' : '❌ No'} |`,
    `| **src/ folder** | ${info.hasSrcFolder ? '✅' : '❌'} |`,
    `| **App Router** | ${info.appRouterPath ? `✅ Yes (\`${info.appRouterPath}/\`)` : '❌ No'} |`,
    `| **Pages Router** | ${info.pagesRouterPath ? `✅ Yes (\`${info.pagesRouterPath}/\`)` : '❌ No'} |`,
    `| **.env** | ${info.hasEnv ? '✅' : '❌'} |`,
    `| **.env.local** | ${info.hasEnvLocal ? '✅' : '❌'} |`,
    `| **.env.example** | ${info.hasEnvExample ? '✅' : '❌'} |`,
    `| **.gitignore** | ${info.hasGitignore ? '✅' : '❌'} |`,
    `| **vercel.json** | ${info.hasVercelJson ? '✅' : '❌'} |`,
    '',
    '## Health Score',
    '',
    `**${result.healthScore} / 100**`,
    '',
    '## Deployment Readiness',
    '',
    `**${result.deploymentReadiness}**`,
    '',
    '## API Routes',
    '',
  ];

  const routeLabel = result.apiRoutes.length === 1 ? 'API route' : 'API routes';
  lines.push(`**${result.apiRoutes.length} ${routeLabel} found**`, '');
  if (result.apiRoutes.length === 0) {
    lines.push('No supported Next.js API route files were detected.', '');
  } else {
    result.apiRoutes.forEach((route) => lines.push(`- \`${route}\``));
    lines.push('');
  }

  lines.push(
    '## Issue Summary',
    '',
    '| Severity | Count |',
    '|----------|-------|',
    `| ${severityEmoji('critical')} Critical | **${counts.critical}** |`,
    `| ${severityEmoji('high')} High | **${counts.high}** |`,
    `| ${severityEmoji('medium')} Medium | **${counts.medium}** |`,
    `| ${severityEmoji('low')} Low | **${counts.low}** |`,
    `| **Total** | **${issues.length}** |`,
    '',
    '## Issues',
    '',
  );

  if (issues.length === 0) {
    lines.push('✅ No issues were detected in this project.', '');
  } else {
    for (const severity of ['critical', 'high', 'medium', 'low'] as Severity[]) {
      const severityIssues = issues.filter((issue) => issue.severity === severity);
      if (severityIssues.length === 0) continue;
      lines.push(`### ${severityEmoji(severity)} ${severityLabel(severity)}`, '');
      for (const issue of severityIssues) {
        lines.push(`#### \`${issue.code}\` — ${issue.title}`, '');
        if (issue.detail) lines.push(`> ${issue.detail}`, '');
      }
    }
  }

  lines.push('## Next Steps', '');
  if (issues.length === 0) {
    lines.push(
      '- Run CodeEq before deploying',
      '- Add `.env.example` if backend or environment variables are introduced',
      '- Use future CodeEq security scans before production',
    );
  } else {
    const nextIssueCodes = issues.slice(0, 3).map((issue) => `\`${issue.code}\``).join(', ');
    lines.push(
      `- Resolve the highest-priority findings first: ${nextIssueCodes}`,
      '- Re-run CodeEq and confirm the health score and readiness improve',
      '- Run CodeEq again before deploying to production',
    );
  }

  lines.push('', '---', '', '*Generated by [CodeEq](https://github.com/alibuildsx/CodeEq) v0.2*', '');
  return lines.join('\n');
}
