import type { ScanResult, Issue, Severity } from '../types/index.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function severityEmoji(s: Severity): string {
  switch (s) {
    case 'critical': return '🔴';
    case 'high':     return '🟠';
    case 'medium':   return '🟡';
    case 'low':      return '🔵';
  }
}

function severityLabel(s: Severity): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function countBySeverity(issues: Issue[]): Record<Severity, number> {
  return {
    critical: issues.filter((i) => i.severity === 'critical').length,
    high:     issues.filter((i) => i.severity === 'high').length,
    medium:   issues.filter((i) => i.severity === 'medium').length,
    low:      issues.filter((i) => i.severity === 'low').length,
  };
}

function frameworkLabel(f: string): string {
  switch (f) {
    case 'nextjs':   return 'Next.js';
    case 'vite':     return 'Vite';
    case 'react':    return 'React';
    case 'express':  return 'Node/Express';
    default:         return 'Unknown';
  }
}

// ─── Markdown report generator ────────────────────────────────────────────────

/**
 * Generates a Markdown string from a ScanResult.
 * The caller is responsible for writing this string to disk.
 */
export function generateMarkdownReport(result: ScanResult): string {
  const { projectInfo: info, issues, targetDir, scannedAt } = result;
  const counts = countBySeverity(issues);
  const totalIssues = issues.length;

  const lines: string[] = [];

  // ── Header ──
  lines.push(`# 🛡️ Project Health Report`);
  lines.push('');
  lines.push(`> Generated by **CodeEq v0.1**`);
  lines.push(`> Scanned: \`${scannedAt}\``);
  lines.push(`> Target: \`${targetDir}\``);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Project Info ──
  lines.push('## 📋 Project Info');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|----------|-------|');
  lines.push(`| **Name** | \`${info.name}\` |`);
  lines.push(`| **Framework** | ${frameworkLabel(info.framework)} |`);
  lines.push(`| **Language** | ${info.language === 'typescript' ? 'TypeScript' : 'JavaScript'} |`);
  lines.push(`| **Package Manager** | ${info.packageManager} |`);
  lines.push(`| **Supabase** | ${info.usesSupabase ? '✅ Yes' : '❌ No'} |`);
  lines.push(`| **src/ folder** | ${info.hasSrcFolder ? '✅' : '❌'} |`);
  lines.push(`| **App Router** | ${info.appRouterPath ? `✅ Yes (\`${info.appRouterPath}/\`)` : '❌ No'} |`);
  lines.push(`| **Pages Router** | ${info.pagesRouterPath ? `✅ Yes (\`${info.pagesRouterPath}/\`)` : '❌ No'} |`);
  lines.push(`| **.env** | ${info.hasEnv ? '✅' : '❌'} |`);
  lines.push(`| **.env.local** | ${info.hasEnvLocal ? '✅' : '❌'} |`);
  lines.push(`| **.env.example** | ${info.hasEnvExample ? '✅' : '❌'} |`);
  lines.push(`| **.gitignore** | ${info.hasGitignore ? '✅' : '❌'} |`);
  lines.push(`| **vercel.json** | ${info.hasVercelJson ? '✅' : '❌'} |`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Issue Summary ──
  lines.push('## 📊 Issue Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| ${severityEmoji('critical')} Critical | **${counts.critical}** |`);
  lines.push(`| ${severityEmoji('high')} High | **${counts.high}** |`);
  lines.push(`| ${severityEmoji('medium')} Medium | **${counts.medium}** |`);
  lines.push(`| ${severityEmoji('low')} Low | **${counts.low}** |`);
  lines.push(`| **Total** | **${totalIssues}** |`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Issues by severity ──
  if (totalIssues === 0) {
    lines.push('## ✅ No Issues Found');
    lines.push('');
    lines.push('Great job! No issues were detected in this project.');
  } else {
    lines.push('## 🔍 Issues');
    lines.push('');

    const severities: Severity[] = ['critical', 'high', 'medium', 'low'];
    for (const sev of severities) {
      const sevIssues = issues.filter((i) => i.severity === sev);
      if (sevIssues.length === 0) continue;

      lines.push(`### ${severityEmoji(sev)} ${severityLabel(sev)}`);
      lines.push('');

      for (const issue of sevIssues) {
        lines.push(`#### \`${issue.code}\` — ${issue.title}`);
        if (issue.detail) {
          lines.push('');
          lines.push(`> ${issue.detail}`);
        }
        lines.push('');
      }
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [CodeEq](https://github.com/alibuildsx/CodeEq) v0.1*');
  lines.push('');

  return lines.join('\n');
}
