import type { Finding, ScanResult, Severity } from '../types/index.js';

function severityEmoji(severity: Severity): string {
  return {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
  }[severity];
}

function severityLabel(severity: Severity): string {
  return severity.charAt(0).toUpperCase() + severity.slice(1);
}

function countBySeverity(findings: Finding[]): Record<Severity, number> {
  return {
    critical: findings.filter((f) => f.severity === 'critical').length,
    high: findings.filter((f) => f.severity === 'high').length,
    medium: findings.filter((f) => f.severity === 'medium').length,
    low: findings.filter((f) => f.severity === 'low').length,
  };
}

function frameworkLabel(framework: string): string {
  return {
    nextjs: 'Next.js',
    vite: 'Vite',
    react: 'React',
    express: 'Node/Express',
  }[framework] ?? 'Unknown';
}

function routerLabel(router: string): string {
  switch (router) {
    case 'app':
      return 'App Router';
    case 'pages':
      return 'Pages Router';
    case 'hybrid':
      return 'Hybrid (App + Pages)';
    case 'none':
    default:
      return 'None';
  }
}

export function generateMarkdownReport(result: ScanResult): string {
  const { projectInfo: info, targetDir, scannedAt } = result;
  const findings: Finding[] = result.findings ?? result.issues ?? [];
  const counts = countBySeverity(findings);

  const lines: string[] = [
    '# 🛡️ Project Health Report',
    '',
    '> Generated by **CodeEq v1.0**',
    `> Scanned: \`${scannedAt}\``,
    `> Target: \`${targetDir}\``,
    '',
    '---',
    '',
    '## Project Info',
    '',
    '| Property | Value |',
    '|----------|-------|',
    `| **Name** | \`${info.name}\` |`,
    `| **Framework** | ${frameworkLabel(info.framework)} |`,
    `| **Language** | ${info.language === 'typescript' ? 'TypeScript' : 'JavaScript'} |`,
    `| **Package Manager** | ${info.packageManager} |`,
    `| **Router** | ${routerLabel(info.router ?? 'none')} |`,
    `| **Database** | ${info.database && info.database !== 'none' ? info.database : 'None'} |`,
    `| **Authentication** | ${info.authProvider && info.authProvider !== 'none' ? info.authProvider : 'None'} |`,
    `| **Deployment** | ${info.deploymentProvider && info.deploymentProvider !== 'none' ? info.deploymentProvider : 'None'} |`,
    `| **Testing** | ${info.testingFrameworks && info.testingFrameworks.length > 0 ? info.testingFrameworks.join(', ') : 'None'} |`,
    `| **Source Files** | ${info.sourceFileCount ?? 0} |`,
    `| **Supabase** | ${info.usesSupabase ? '✅ Yes' : '❌ No'} |`,
    `| **src/ folder** | ${info.hasSrcFolder ? '✅' : '❌'} |`,
    `| **App Router** | ${info.appRouterPath ? `✅ Yes (\`${info.appRouterPath}/\`)` : '❌ No'} |`,
    `| **Pages Router** | ${info.pagesRouterPath ? `✅ Yes (\`${info.pagesRouterPath}/\`)` : '❌ No'} |`,
    `| **.env** | ${info.hasEnv ? '✅' : '❌'} |`,
    `| **.env.local** | ${info.hasEnvLocal ? '✅' : '❌'} |`,
    `| **.env.example** | ${info.hasEnvExample ? '✅' : '❌'} |`,
    `| **.gitignore** | ${info.hasGitignore ? '✅' : '❌'} |`,
    `| **vercel.json** | ${info.hasVercelJson ? '✅' : '❌'} |`,
    '',
    '## Health Score',
    '',
    `**${result.health?.overall ?? result.healthScore} / 100**`,
    '',
  ];

  if (result.health?.categories) {
    const cats = result.health.categories;
    lines.push(
      '| Category | Score |',
      '|----------|-------|',
      `| Security | **${cats.security} / 100** |`,
      `| Configuration | **${cats.configuration} / 100** |`,
      `| Code Health | **${cats.codeHealth} / 100** |`,
      `| Dependencies | **${cats.dependencies} / 100** |`,
      `| Deployment | **${cats.deployment} / 100** |`,
      '',
    );
  }

  lines.push(
    '## Deployment Readiness',
    '',
    `**${result.deploymentReadiness}**`,
    '',
    '## API Routes',
    '',
  );

  const routeLabel = result.apiRoutes.length === 1 ? 'API route' : 'API routes';
  lines.push(`**${result.apiRoutes.length} ${routeLabel} found**`, '');
  if (result.apiRoutes.length === 0) {
    lines.push('No supported Next.js API route files were detected.', '');
  } else {
    result.apiRoutes.forEach((route) => lines.push(`- \`${route}\``));
    lines.push('');
  }

  lines.push(
    '## Issue Summary',
    '',
    '| Severity | Count |',
    '|----------|-------|',
    `| ${severityEmoji('critical')} Critical | **${counts.critical}** |`,
    `| ${severityEmoji('high')} High | **${counts.high}** |`,
    `| ${severityEmoji('medium')} Medium | **${counts.medium}** |`,
    `| ${severityEmoji('low')} Low | **${counts.low}** |`,
    `| **Total** | **${findings.length}** |`,
    '',
    '## Issues',
    '',
  );

  if (findings.length === 0) {
    lines.push('✅ No issues were detected in this project.', '');
  } else {
    for (const severity of ['critical', 'high', 'medium', 'low'] as Severity[]) {
      const severityFindings = findings.filter((f) => f.severity === severity);
      if (severityFindings.length === 0) continue;
      lines.push(`### ${severityEmoji(severity)} ${severityLabel(severity)}`, '');
      for (const finding of severityFindings) {
        lines.push(`#### \`${finding.code}\` — ${finding.title}`, '');

        if (finding.category || finding.confidence || finding.deploymentImpact) {
          const metaParts: string[] = [];
          if (finding.category) metaParts.push(`**Category:** ${finding.category}`);
          if (finding.severity) metaParts.push(`**Severity:** ${severityLabel(finding.severity)}`);
          if (finding.confidence) metaParts.push(`**Confidence:** ${finding.confidence}`);
          if (finding.deploymentImpact) metaParts.push(`**Deployment Impact:** ${finding.deploymentImpact}`);
          lines.push(`> ${metaParts.join(' | ')}`, '>');
        }

        if (finding.summary) {
          lines.push(`> **Summary:** ${finding.summary}`, '>');
        } else if ((finding as { detail?: string }).detail) {
          lines.push(`> ${(finding as { detail?: string }).detail}`, '>');
        }

        if (finding.whyItMatters) {
          lines.push(`> **Why it matters:** ${finding.whyItMatters}`, '>');
        }

        if (finding.remediation) {
          lines.push(`> **Remediation:** ${finding.remediation}`, '>');
        }

        if (finding.file) {
          const loc = finding.line ? `${finding.file}:${finding.line}` : finding.file;
          lines.push(`> **Location:** \`${loc}\``, '>');
        }

        if (finding.evidence) {
          lines.push(`> **Evidence:** \`${finding.evidence}\``, '>');
        }

        lines.push('');
      }
    }
  }

  lines.push('## Next Steps', '');
  if (findings.length === 0) {
    lines.push(
      '- Run CodeEq before deploying',
      '- Add `.env.example` if backend or environment variables are introduced',
      '- Use future CodeEq security scans before production',
    );
  } else {
    const nextIssueCodes = findings.slice(0, 3).map((f) => `\`${f.code}\``).join(', ');
    lines.push(
      `- Resolve the highest-priority findings first: ${nextIssueCodes}`,
      '- Re-run CodeEq and confirm the health score and readiness improve',
      '- Run CodeEq again before deploying to production',
    );
  }

  lines.push('', '---', '', '*Generated by [CodeEq](https://github.com/alibuildsx/CodeEq) v1.0*', '');
  return lines.join('\n');
}
